### ISSUE TITLE
multiplier mismatch

### ISSUE THREAD

**Issue by hailinzeng** [dawsonjon/fpu#13]
Hi, dawsonjon

I run C-to-RTL formal verification on the multiplier and found there is a mismatch.

input:
a : 32'h7f80_0000 (infinity)
b : 32'h0

output:
C implementation : 32'hFFC00000 (NAN)
RTL implementation : 32'h7f80_0000 (infinity)

I googled the IEEE 754 standard and found this table : 

Table 4. Multiplication of operands.
![image](https://user-images.githubusercontent.com/1791200/33803437-0a5648ce-ddcb-11e7-9a91-17561252facd.png)

[ref: http://techdocs.altium.com/display/FPGA/IEEE+754+Standard+-+Overview]

It seems multiple an Infinity to zero is NaN.

**Comment by hailinzeng** [comment]
I have uploaded the testbench in [here](https://github.com/exa-mining/oss-c-rtl/blob/493297d541ee6b2a5fa152c136cb0b51fde51f1d/ieee754/mul_inf_zero/testbench.v#L1-L243).

And here is the waveform.
![waveform](https://raw.githubusercontent.com/exa-mining/oss-c-rtl/4e54074f3eb6e567f628f4746717c60f20d7b24c/ieee754/mul_inf_zero/waveform.png)

**Comment by dawsonjon** [comment]
Thanks,
It looks like my test bench was not doing a very good job of checking "special" values. I also found a similar error in the adder when adding infinities of different signs. I will run some similar tests on the double precision versions, and then check in a fix.
Jon
